// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzdtgjtajrfjavaynivp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6ZHRnanRhanJmamF2YXluaXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNTEwOTgsImV4cCI6MjA1NTcyNzA5OH0.bWfQW3_9_HNDnYeumT9cUwYU3xQkTW-xgRpigUg19pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);